# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GrandLoginRegisterVC' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GrandLoginRegisterVC
  pod 'HYBHelperKit'


  target 'GrandLoginRegisterVCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GrandLoginRegisterVCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
